# Generated by Django 3.0.4 on 2020-07-14 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allergy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateCompleted', models.DateField(blank=True, null=True)),
                ('New_Allergy', models.CharField(choices=[('Shellfish', 'Shellfish'), ('Milk', 'Milk'), ('Eggs', 'Eggs'), ('Soy', 'Soy'), ('Wheat', 'Wheat'), ('Fish', 'Fish'), ('Peanuts', 'Peanuts'), ('Walnuts', 'Walnuts'), ('Citrus', 'Citrus'), ('Strawberry', 'Strawberry')], max_length=70)),
                ('description', models.TextField(default=False)),
                ('Life_threatening', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
