# Generated by Django 3.0.4 on 2020-07-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Hospital_Location', models.CharField(max_length=400)),
                ('hospitalization_photo', models.ImageField(upload_to='hospitalizations')),
            ],
        ),
    ]
