# Generated by Django 3.0.4 on 2020-07-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergy', '0004_hospitalization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hospitalization',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
