# Generated by Django 3.0.4 on 2020-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy', '0006_auto_20200716_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateCompleted', models.DateField(blank=True, null=True)),
                ('Name_of_hospital', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='hospitalizations')),
            ],
        ),
        migrations.AlterField(
            model_name='allergy',
            name='New_Allergy',
            field=models.CharField(choices=[('Shellfish', 'Shellfish'), ('Milk', 'Milk'), ('Eggs', 'Eggs'), ('Soy', 'Soy'), ('Wheat', 'Wheat'), ('Fish', 'Fish'), ('Peanuts', 'Peanuts'), ('Walnuts', 'Walnuts'), ('Citrus', 'Citrus'), ('Strawberry', 'Strawberry')], max_length=70),
        ),
    ]
