# Generated by Django 3.0.4 on 2020-07-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergy', '0007_auto_20200717_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hospitalizations',
        ),
    ]
