# Generated by Django 3.0.4 on 2020-07-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergy', '0009_hospitalizations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hospitalizations',
        ),
    ]
